#!/bin/bash

if ! git ls-remote origin > /dev/null; then
    git init
    git remote add origin https://github.com/slashworks/control.git
fi
git fetch --tags
latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
git checkout $latestTag