imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler:
        only_exceptions: false
web_profiler:
    toolbar: false
    intercept_redirects: false
monolog:
    handlers:
        applog:
            type: rotating_file
            path: '%kernel.logs_dir%/error.log'
            level: error
            max_files: 5
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/debug.log'
            action_level: debug
            max_files: 5
assetic:
    use_controller: true
