imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  de
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SlashworksBackendBundle:Form:form_div_layout.html.twig'
        - 'SlashworksBackendBundle:Form:form_row.html.twig'
    paths:
            "%kernel.root_dir%/../src/Slashworks/AppBundle/Resources/views": app_theme
            "%kernel.root_dir%/../src/Slashworks/BackendBundle/Resources/views": app_theme



# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [SlashworksBackendBundle,SlashworksAppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    dbal:
        driver:               %database_driver%
        user:                 %database_user%
        password:             %database_password%
        dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
  slashworks_backendbundle_install:
    class: Slashworks\BackendBundle\Form\Type\InstallType
    tags:
      - {name: form.type}